### PR TITLE
Enable AppVeyor Continous Integration and Testing

### PR DESCRIPTION
**Pull request by MarcosMeli**
It will looks like https://ci.appveyor.com/project/MarcosMeli/docnet when enabled

### CODE REVIEW

**Comment by FransBouma** [comment]
Appreciated, but I don't use AppVeyor. So a question from my side: if I add this file, that makes life easier for people who do, I recon? Though I see little value for adding it if I don't use it myself, to be honest.

**Comment by MarcosMeli** [comment]
Frans

Sorry that I did not ask before the PR, in fact if you add your file you also need to enter appveyor and enable this repo. It is free for open source software at github

Doing that you get all the Commits and PRs automatically tested and checked and you can get coverage, automatic deploy night builds, etc

For example in this PR: https://github.com/MarcosMeli/FileHelpers/pull/174 You can see this image

image

That the build is checked so you don't to manual merge it to check if tests pass

Just my 2 cents, no problem at all if you think is not needed, just close the PR

Best Regards

**Comment by FransBouma** [comment]
:) Yeah it looks like a nice service, thing is, I run the tests before committing locally, and if something fails, I'll correct it first. It's my way of working (I write ORMs, and CI for ORMs is a big pain anyway due to the fact you have to spin up DB instances for tests, so they're often done when necessary, not when a commit happens, as things have to be ready), and that doesn't match everyone else's ;) 

I see the added value though :) For a PR I always clone it separately, run the tests (which are there in the clone too), run them there, and can debug tests if needed. So I don't see myself relying on this in the future. Sorry, for your time on this, Marcos!

**Comment by MarcosMeli** [comment]
Frans

No problem at all, I'm doing open source for years so I perfectly understand. I was trying to integrate some open tools :+1: 

If you need my time in any integration I would love to help.

I'm in the process of release an open source library that make runnable code examples into docs

For example this file

https://github.com/MarcosMeli/FileHelpers/blob/master/FileHelpers.Examples/Examples/10.QuickStart/10.ReadFileDelimited.cs

is automatically converted into: 

http://www.filehelpers.net/example/QuickStart/ReadFileDelimited/

The parser uses Roslyn for the convertion and you get the HTML but also a Runnable exe with the examples :beers: 

Using DocNet looks like a great complement, I will look forward for integration

Thanks for you time too, I long time follower of your blogs and work !!
Marcos

**Comment by FransBouma** [comment]
:) I'll let you know if / when I'll add appveyor integration! That example looks great btw :) Cheers!

**Pull request closed without merging**
