### PR TITLE
Fix invalid path in some references

### PR DESCRIPTION
**Pull request by MarcosMeli**
Did not work on a clean clone

### CODE REVIEW

**Comment by FransBouma** [comment]
Ah yes, forgot to update the path. 

But your pull request contains lots of stuff that's not going to be merged: the travis file has to go, and you changed the .net version as well. Don't do that. 

Only the file path change is going to be merged.

**Comment by MarcosMeli** [comment]
Thanks Frans

Yes the other commits were for my fork but Git for windows added the commits to the PR too, sorry I will try to delete the other commits o create a new PR

I was trying to make my fork to work on mono with travis so I can send another PR with travis integration. But if change the TargetFramework is a no change, so I will try with AppVeyor

https://travis-ci.org/MarcosMeli/FileHelpers

https://ci.appveyor.com/project/MarcosMeli/filehelpers/branch/master

Best Regards

**Comment by MarcosMeli** [comment]
I will close this PR

I just edit the files directly in github so you have other two PR with the changes

Sorry for the trouble

Thanks for the library !!

**Comment by MarcosMeli** [comment]
It works I fine in AppVeyor

I will revert the changes and create a AppVeyor config if you want

Thanks

**Pull request closed without merging**
